apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: antrea-capture

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml

images:
  - name: antrea-capture
    newTag: latest
